dist: xenial
language: python
python:
- '3.7'
install:
- pip3 install --upgrade pip
- pip install coveralls
- pip install pytest
- npm install lcov-parse
script: pytest test.py -v --tb=no
after_success:
- coveralls
notifications:
  webhooks:
  - http://str-expert-cert-3359.botics.co/api/v1/challenge/check_builds/
env:
  global:
  - secure: bbHjSUuG/sC5lhIHNJPwJMLDtEEB7Mr5D+krcXO1yRh029aOZiqNx5IVatOHNJ2WJ+idUIQ5Ia4G4rx03er+wQKLA11cHt/jfJJB2RgXVhvknhMd++cf+PGAyJRbFZndKw5Yq5//6+pFcgJK2CdunwZTcjbiUlre8WSehU57IwhxmXEWN7Uz6vZY8ZzqUZkZF80s46VeKa78VN1T1vkCuCEq0TkohFP0ayML/frinPed2QsBB/iCPPYaeqH+rrUJi1BFba5QTiTrUqHv4WXkIw/suRgFJL5WXNLScL3f6oLYqUvKN69dh/opdca+XV6bZ/l06iWik+8fvJvRTcJw+S5vqr7/NnmGHkD4307twJ4+cTzyfL+3VA8MjVX8kCqHNN04mdn5eaxGLKzBbmRABkOwdnOlUj5zppumogUGPfnwLbGZ2IZcltVWZRCP5caFnrXhCjmZtaIOq7Df5QNl982NsK0y6jtJ/61nFSy7EwHvZtaSTcresJ+2jhyXa17Pbk4FzyKw7WzaxzXHHqSqCQ9tVSm92LjT+EjhTJUVwadtmJo5q9zm0OWZuV4L6QZtzwDH208R48FP1qudLq/lpk6/IdEyHn2sPASDZpFQi8tHZukivmfKOdN7D6C5gZdn835WL63ryjEnAGKH0mgqitfM7pjs8k4kbbcKiebdiDA=
  - secure: oKkfn16V4pbeWeQKfRLnDuguShqUt8+U/VW4TBQF7ZkBc9yZ9c8DxfZxLLHVL22fLn9vLWDuA46Aom2jNNfvGjMb16NjFxGOzUuZvGtojxgQ82Z+chfmT4eLxTr2n3FbYxKY3fyM5Z1nhWzU/YCVLmKUuGJwW6E0Gu7flikRisl53a8ZWCWkFOlNGjkWTWM9xtxU/e3kKHzqv+7e5wD32qbnxIicQUaPa8rBUAZ12irsXPL5PGxZASz93bzlgPRs+wLQstgemIhJiBUvM/x905xNWSPG+kqQKewPN4PolP/rguFi43xlP8KcEg1vqrhN7HzY0EUjTkuimRTF+du0/13jA1yCemitBxPzzSUsSDQ3YWgiPqK7cnKEdZGTkSc+8tCMNu9J3I2Co6UVnbolyCuqYZ9+TpvYXe/iPyZPfVuvo6sPeF5mV05/rM/D8PLI8ATT+oA5ZPebQVu4MwgtcCf/iJIjFsL2ObkjYvM0K5Z9DkrT704d6j6GLIL7yU6iLmzdZW4m/XvJAtaD2X/os7Vr4DZVLe21sfA5JVW8/hj6nXqfhWg7yrsC27MQ23gjeNjvJlKpnzAJh8LQxSgHVUX/Cd6b4cszCn/HE8KGLlhwzHIUbgkiSUAFTyoD53+0/vYjZ2S8UrCmLpD+KgFjUPZzsVP2CFLaJZDqnwND2B0=
