dist: xenial
language: python
python:
- '3.7'
install:
- pip3 install --upgrade pip
- pip install coveralls
- pip install pytest
- npm install lcov-parse
script: pytest test.py -v --tb=no
after_success:
- coveralls
notifications:
  webhooks:
  - http://str-expert-cert-3359.botics.co/api/v1/challenge/check_builds/
env:
  global:
    secure: uDyBcun905y8x42Pcq2aa/lc0uj7r4C4457YmZTfGeh6DUXdtD33Rlmv0ISR5GSObYfvkvprzoD7mao4gWx21uSEMFvDfdR5YL1KG+Sxzv5WnVwEPogUiUM6jU/VczOzcmiy5+eCJ0vFNPoeMQSpUlodukrUHlJ35D9pM+UQOY9xPJ7zNC5WklHhveUWeOH4Ui7QIk85vdmBPDKkDl7gH5sOpLwyzeLRQQq0ATlfBmuxDo/anDFlStg+rFfvAXolCwj3eW7fd53M4dnKP7mXqMaZJv7dgaujYni2rLViC6qIGstMNzNOYWKyyJu2kw41qSr1yxDHh8SzzCvGsS0zSjGF1GN6zi/F7EKVoh9x4tCAummtJlEvu9BHyfhShFpP3LmYvaOOPP9/0Hgiuvcd+Yw8SiHZ5TLWAn2nNlVF8A/4wJTBRkFOZnkHxkwaQf/5wbT2/dGLGcxJrGxkvJ6R1XdiVGziDH8Ecr329I8udR43ab5S3ffCxfMXAUhb8XzNphzsAtppoIYoMjnWkWzXzwtgterpumq3NQSwKIoGolM9oTJma42G3vrUgYPak6tcutMDw9nGjI5Lio9lLKYKyfOjQpf5G50PcI47oSGX7u7vI3S46i42y5scRK2MPd8z3GIXVeOkBEc/h9DkYHVuPRotK6tku9eOZK1uRVakcso=
